# base-image for golang on any machine using a template var
FROM resin/%%RESIN_MACHINE_NAME%%-golang:1.9

ENV INITSYSTEM on

RUN apt-get update && apt-get install --no-install-recommends -qy libopus-dev libasound2-dev

COPY . $GOPATH/src/github.com/mysteryhunt/hunt2018-radio-client

WORKDIR $GOPATH
RUN go install github.com/mysteryhunt/hunt2018-radio-client

CMD ["./bin/hunt2018-radio-client"]
