# base-image for golang on any machine using a template var
FROM resin/%%RESIN_MACHINE_NAME%%-golang:1.9-slim

ENV INITSYSTEM on

RUN apt-get update && \
  apt-get install --no-install-recommends -qy pkg-config libopus-dev libasound2-dev libudev-dev alsa-utils

COPY . $GOPATH/src/github.com/mysteryhunt/hunt2018-radio-client

WORKDIR $GOPATH
RUN go install github.com/mysteryhunt/hunt2018-radio-client

CMD ["./bin/hunt2018-radio-client"]
